OPCIONS = -D_JUDGE_ -D_GLIBCXX_DEBUG -O2 -Wall -Wextra -Werror -Wno-sign-compare -std=c++11

program.x: program.o Problemas.o Curso.o Cursos.o Sesion.o Sesiones.o Usuario.o Usuarios.o

Problmeas.o: Problemas.cc Problemas.hh
	g++ -c Problemas.cc $(OPCIONS)

Curso.o: Curso.cc Curso.hh
	g++ -c Curso.cc $(OPCIONS)

Cursos.o: Cursos.cc Cursos.hh
	g++ -c Cursos.cc $(OPCIONS)

Sesion.o: Sesion.cc Sesion.hh
	g++ -c Sesion.cc $(OPCIONS)

Sesiones.o: Sesiones.cc Sesiones.hh
	g++ -c Sesiones.cc $(OPCIONS)

Usuario.o: Usuario.cc Usuario.hh
	g++ -c Usuario.cc $(OPCIONS)

Usuarios.o: Usuarios.cc Usuarios.hh
	g++ -c Usuarios.cc $(OPCIONS)

clean:
	rm *.o
	rm *.x
